### ISSUE TITLE
RemoteIntent not found error

### ISSUE THREAD

**Issue by andrew-codechimp** [googlesamples/android-WearVerifyRemoteApp#2]
When trying to use this sample I'm getting errors trying to resolve Remote Intent

error: package com.google.android.wearable.intent does not exist
error: cannot find symbol variable RemoteIntent

I'm getting the same on my own project which implemented this as well, updating all dependencies to the latest versions didn't resolve the issue either.

**Comment by codingjeremy** [comment]
This issue has been migrated to the Wear OS sample repo, so I am closing here. Thanks!
